### ISSUE TITLE
https vs http

### ISSUE THREAD

**Issue by fpuigb** [tsawyer/allmon2#11]
Hi, is there a way to use https for allmon2 instead of http?

**Comment by JoshuaCarroll** [comment]
@fpuigb Have you enabled HTTPS on your server?  If not, just follow these instructions: https://certbot.eff.org/

Let's Encrypt is easy and very secure.

**Comment by tsawyer** [comment]
@fpuigb yes @JoshuaCarroll is correct. Closing this issue.
